# Generated by Django 3.2.8 on 2021-11-06 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=30)),
                ('daily_paragraphs', models.IntegerField()),
                ('daily_txt_reminders', models.BooleanField(default=False)),
                ('weekly_txt_summary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('chapter_number', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('paragraph_number', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sentence_1', models.CharField(max_length=150)),
                ('sentence_2', models.CharField(max_length=150)),
                ('sentence_3', models.CharField(max_length=150)),
                ('sentence_4', models.CharField(max_length=150)),
                ('sentence_5', models.CharField(max_length=150)),
                ('sentence_6', models.CharField(max_length=150)),
                ('sentence_7', models.CharField(max_length=150)),
                ('sentence_8', models.CharField(max_length=150)),
                ('sentence_9', models.CharField(max_length=150)),
                ('sentence_10', models.CharField(max_length=150)),
                ('sentence_11', models.CharField(max_length=150)),
                ('sentence_12', models.CharField(max_length=150)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.chapter')),
            ],
        ),
    ]
